### ISSUE TITLE
Share Pipeline Configuration

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline#119]
There are two configurations that are at pipeline level that needs to be shared to Plugins,

1. Number of Processors - This is required for Stateful processors. (Already a [TODO](https://github.com/AustinTag/simple-ingest-transformation-utility-pipeline/blob/d60ea60153a5726571c89a098e8b1921ea0002c9/situp-plugins/mapdb-processor-state/src/main/java/com/amazon/situp/plugins/processor/state/MapDbProcessorState.java#L29))
2. Name of the pipeline - This is required for logging purpose, given that logs are the only way to track things in situp having the logs with Pipeline name will help us debug things. (check on this with @yadavcbala )

**Comment by chenqi0805** [comment]
I see those fields in the `PipelineParser` and `PipelineConfiguration`. Need to decide what reserved field name for the two in `PluginSettings`.

**Comment by chenqi0805** [comment]
Also, since we are concatenating pipelines, is number of processor supposed to be setting at top level or each pipeline level?
