### ISSUE TITLE
Implement standard grpc health check

### ISSUE THREAD

**Issue by wrijeff** [opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline#152]
Our current health check is based of HTTP1.1 as the ALB preview was did not support gRPC. ALB now supports gRPC health check. Implement HealthGrpc compliant with  https://github.com/grpc/grpc/blob/master/doc/health-checking.md and add it to the server (if health checking is enabled).

**Comment by kowshikn** [comment]
As discussed offline, we should add flag for ProtoReflection so that users can use grpcurl and test the source.

**Comment by wrijeff** [comment]
> As discussed offline, we should add flag for ProtoReflection so that users can use grpcurl and test the source.

Created https://github.com/opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline/issues/160 for this.
