### ISSUE TITLE
[ES sink]Test logger in ES sink

### ISSUE THREAD

**Issue by chenqi0805** [opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline#19]
This issue is to track the test coverage on logger in ES sink:

https://github.com/opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline/blob/30f35e4abb8f4354ec6b93691e4c6f2f84e42637/situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSink.java#L51

Ref: https://www.baeldung.com/junit-asserting-logs

**Comment by kowshikn** [comment]
I'm not sure if we should do this, I would rather test the exceptions and state instead of log messages. @erosas @laneholloway ?

**Comment by laneholloway** [comment]
Testing on exception and state would be what I prefer, asserting based on log results is a little iffy.
